### ISSUE TITLE
Radio buttons

### ISSUE THREAD

**Issue by jano23** [thomhines/validin#1]
I have everything working except for radio buttons.
Here is a code example:
<label for="test">test1<input name="test" type="radio" value="testone" validate="required" /></label>
<label for="test2">test2<input name="test" type="radio" value="testtwo" /></label>

If I don't select any options and go to the next field, no errors are generated. I can't submit the form until I check one, but no errors. (except for the submit button error)

**Comment by thomhines** [comment]
I realized this was a problem recently and started working on some updates. I'll try to finalize those and update the repo this week. Thanks for letting me know!

**Comment by jano23** [comment]
Perfect! 
Thanks Thom

**Comment by thomhines** [comment]
I've just uploaded a small round of changes, including radio button support. Let me know if that fixed it for you!

**Comment by jano23** [comment]
Trying it...
On a group of radio buttons, do I add "required" to the first one only? 
On the sample page, you only have one radio button

**Comment by thomhines** [comment]
It seems to work either way! You can either put the "required" attribute on just one radio button, or all of them, and the browser should require one (and only one) radio button be selected.

**Comment by jano23** [comment]
Thank you sir

**Comment by thomhines** [comment]
My pleasure! Thanks for letting me know about this issue!
