### ISSUE TITLE
server side validation

### ISSUE THREAD

**Issue by iman64** [thomhines/validin#2]
Hello
I've tried to add server-side validation to this script but I'm having trouble.
Please add server-side validation.
Thank

**Comment by thomhines** [comment]
Hi! Sorry, but this is written in javascript and will only ever be able to support client-side validation. You'll have to use a server-side framework or language to support validating inputs on the server.

**Comment by iman64** [comment]
OK.
but can you add method for ajax call and stop form submit until server return true response ? on line 160 or line 172
i tried to do it but form submitted before server return valid or invalid response.
please help me for completting my script.

**Comment by thomhines** [comment]
Hmm... That's an interesting idea. Are you submitting an ajax call when the user tries to submit the form? Or is the ajax call being sent to populate an input?

I can't think of how I could implement something like that in a way that would be general enough to work for a lot of use cases, though, and it's a bit out of the scope of what I'm trying to do with validin. 

That said, you can probably make some of this work yourself by replacing the submit button on your form with a button that has a custom function that prevents the form from submitting, runs the ajax call, then triggers the form to submit if the ajax call returns the value you want. Something like this:

```javascript
$('.submit_button').click(function(e) {
	// Prevent form for submitting
	e.preventDefault();
	e.stopPropagation();
	
	let $form = $(this).closest('form')
	// In the ajax callback function, check the response
	ajax(data, function(response) {
		// If the response is valid, submit the form
		if(response == 'valid') $form.trigger('submit')
	})
})
```

**Comment by iman64** [comment]
[validin.txt](https://github.com/thomhines/validin/files/12892872/validin.txt)
I have made some changes in the code of this script.
Everything works fine especially server-side validation, except for the final submission of the form, which does not work with this commented text: 
//this not worked
In line 427
the form not submitted until all validation rules passed and return variable: Validated = true;
but $form.submit(); not worked !!

i change the attribute for check.
validate changed to data-validation
added data-validation-url for ajax call url
added data-validation-req-params for ajax data parameters

i dont want to replace submit input with simple button
if you optimize this codes your script will be the very simple and well validator for develop.
thanks so mutch
